name: CD Test

on:
  push:
    branches:
      - develop

jobs:
  build-web:
    name: Web Build and Release to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Clone Flutter repository with stable channel
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Deploy Flutter web app to github pages
        uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /AppOintment/
