name: CI

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  unit-test:
    name: Continuous Integration Jobs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Clone Flutter repository with stable channel
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Install Dependencies
        run: flutter pub get

      - name: Format
        run: flutter format --dry-run --set-exit-if-changed lib/ test/

      - name: Analyze
        run: flutter analyze

      - name: Run Tests
        run: flutter test --coverage --machine > test-results.json

      - name: Generate Test Report
        uses: dorny/test-reporter@v1.4.2
        with:
          name: test-results
          path: test-results.json
          reporter: flutter-json

      - name: Check Test Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          min_coverage: 50
