name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    name: Format, Analyze, and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Clone Flutter repository with stable channel
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Install Dependencies
        run: flutter pub get

      - name: Format
        run: flutter format --dry-run --set-exit-if-changed lib/ test/

      - name: Analyze
        run: flutter analyze

      - name: Run Tests
        run: flutter test --coverage --machine > test-results.json

      - name: Generate Test Report
        uses: dorny/test-reporter@v1.4.2
        with:
          name: test-results
          path: test-results.json
          reporter: flutter-json

      # - name: Remove generated files from coverage
      #   run: |
      #     dart pub global activate remove_from_coverage
      #     dart pub global run remove_from_coverage:remove_from_coverage -f coverage/lcov.info -r '\.g\.dart$' -r '\.gr\.dart$'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
